config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users, only: [:new, :create] do 
    resources :tasks, only: [:index, :show, :new]
  end 

  resources :projects
  resources :tasks


  # Sessions Routes #
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  post '/logout' => "sessions#destroy"
  get '/auth/facebook/callback' => "sessions#facebook"
  # Sessions Routes #

  # ------ #

  # Custom Routes #
  get '/about' => "about#index"
  get '/dashboard' => "users#dashboard"
  get '/users/most_projects' => "users#most_projects"
  # Custom Routes #

  # ------ #

  # Users Routes #
  get '/signup' => "users#new"
  post '/signup' => "users#create"
  post '/users/:id/tasks/new' => "tasks#create"
  # Users Routes #

  # ------ #

  # Tasks Routes #
  get '/tasks/:id/complete' => "tasks#complete"
  delete '/task/:id' => "tasks#destroy"
  delete '/project/:id' => "projects#destroy"
  # Tasks Routes # 

end

app/models/task.rb
class Task < ActiveRecord::Base
    
    belongs_to :user
    belongs_to :project

    validates :description, :due_date, presence: true
    validate :due_date_cannot_be_in_the_past

    scope :completed_tasks, -> {where(completed: true)}
    scope :over_due, -> {where("due_date > ?", Date.today)}

    def due_date_cannot_be_in_the_past
        if due_date.present? && due_date < Date.today
            errors.add(:due_date, "can't be in the past")
        end
    end

end 

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :require_login
    before_action :set_task, only: [:edit, :update, :destroy, :complete]
  
    def index
        @tasks = current_user.tasks
        @project = Project.find_by(:user_project_id => current_user.id) 
    end
  
    def new
        @task = Task.new(user_id: @user.id)
    end
  
    def create
        @task = Task.new(task_params)
        @task.assigned_by = current_user.id
        if @task.save
            redirect_to projects_path
        else
            render :new
        end
    end
  
    def edit

    end
  
    def update
      if @task.update(task_params)
        redirect_to projects_path
      else
        render :edit
      end
    end
  
    def complete
        if current_user.id == @task.user_id
            @task.update(completed: true)
            redirect_to '/tasks'
        else
            flash[:error] = "You cannot complete a task that was not assigned to you."
            redirect_to '/tasks'
        end 
    end
  
    def destroy
        if current_user.id != this_task.user_id
            flash[:error] = "You cannot destroy a task that doesn't belong to you."
            redirect_to projects_path
        end 
        this_task.destroy
        redirect_to tasks_path
    end
  
    private
  
    def set_task
        @task = Task.find(params[:id])
    end

    def this_task
        Task.find(params[:id])
    end 
  
    def task_params
        params.require(:task).permit(:due_date, :description, :user_id, :project_id)
    end
end
  

app/views/tasks/_completed.html.erb
<table style="width:100%">
    <tr>
        <th>Task</th>
        <th>Due Date </th>
        <th>Assigned To</th>
        <th>Delete</th>
        <th>Complete</th>
    </tr>

    <% @tasks.all.each do |task| %>
        <% if task.completed %>
        <tr>
            <td><%= task.description %></td>
            <td> <%= task.due_date.strftime("%B %d, %Y") unless task.due_date.nil?  %> </td>
            <% if @user.first_name.nil? %>
                <td> <%= task.user.name %> </td>
            <% else %>
                <td> <%= task.user.first_name %>
            <% end %>
            
            <% if task.user_id = @user.id %>
                <td> <%= button_to "Delete Task", task_path(task), method: :delete %> </td>
            <% else %>
                <td></td>
            <% end %>
            <td> Completed </td>
        </tr>
        <% end %>
    <% end %>
</table>

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
    <div class="error_msg">
        <h2>
        <%= pluralize(@task.errors.count, "error") %>
        prohibited this post from being saved:
        </h2>

        <ul>
            <% @task.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>


<br><br><br><br><br>
<%= form_for(@task) do |f| %>
    <div>
        <%= f.label :description, "Description:" %>
        <%= f.text_field :description, class: "task-form-field" %>
    </div>
    <div>
        <%= f.label :due_date, "Due Date:"%>
        <%= f.date_select :due_date, class: "task-form-field" %>
    </div>
    <div>
        <%= f.label :project_id, "Please choose the project for this task:" %><br>
        <%= f.collection_select :project_id, Project.all, :id, :name %>
    </div>

    <div>
      <%= f.hidden_field :user_id  %>
      <%= f.label :user_id, "Select the User for this task:" %><br>
      <%= f.collection_select :user_id, User.all, :id, :first_name %>
    </div>

    <div>
      <%= f.submit "Submit", class: "task-submit" %>
    </div>
  <% end  %>
</div>

app/views/tasks/_tasklist.html.erb
<table class="table-labels">
  <thead>
    <tr>
      <th scope="col">Task</th>
      <th scope="col">Project</th>
      <th scope="col">Due Date </th>
      <th scope="col">Assigned To</th>
      <th scope="col">Assigned By</th>
      <th scope="col">Edit/Delete</th>
      <th scope="col">Complete</th>
    </tr>
  </thead>
  <tbody style="width:100%">
    <% @tasks.all.each do |task| %>
      <% if !task.completed %>
        <tr>
            <td><%= task.description %></td>
            <td> <%= task.project.name %> </td>
            <td> <%= task.due_date.strftime("%B %d, %Y") unless task.due_date.nil?  %> </td>
            <td> <%= task.user.first_name %> </td>

            <td> <%= task_owner(task) %></td>
            
            <% if current_user.id == task.assigned_by %> 
              <td> <%= link_to "Edit", edit_task_path(task) %> <hr> <%= button_to "Delete Task", task_path(task), method: :delete %></td>
            <% else %>
              <td></td>
            <% end %>

            <% if task.user_id == current_user.id %>
              <td> <a class="" href="/tasks/<%= task.id %>/complete">Complete</a></td>
            <% else %>
              <td>Not Complete</td>
            <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/tasks/edit.html.erb
<%= render 'form', :locals => {:@task => @task} %>

app/views/tasks/index.html.erb
<br><br><br><br>
<div class="flash-error">
    <% if !flash[:error].nil? %>
        <%= flash[:error] %>
    <% end %>
</div>
<div class="dash-container-tasks">
    <button class="create-tasks"><%= link_to "Create a New Task", new_user_task_path(@user) %></button>
</div><br>

<div class="table-labels">
    <%= render 'tasklist', :locals => {:@tasks => @tasks} %>
</div>

<br><br>

<div class="">
    <h2><-Completed Tasks-></h2><hr><br>
    <%= render 'completed', :locals => {:@tasks => @tasks} %>
</div>

app/views/tasks/new.html.erb
<%= render 'tasks/form', :locals => {:@task => @task}%>