config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users, only: [:new, :create] do 
    resources :tasks, only: [:index, :show, :new]
  end 

  resources :projects
  resources :tasks


  # Sessions Routes #
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  post '/logout' => "sessions#destroy"
  get '/auth/facebook/callback' => "sessions#facebook"
  # Sessions Routes #

  # ------ #

  # Custom Routes #
  get '/about' => "about#index"
  get '/dashboard' => "users#dashboard"
  get '/users/most_projects' => "users#most_projects"
  # Custom Routes #

  # ------ #

  # Users Routes #
  get '/signup' => "users#new"
  post '/signup' => "users#create"
  post '/users/:id/tasks/new' => "tasks#create"
  # Users Routes #

  # ------ #

  # Tasks Routes #
  get '/tasks/:id/complete' => "tasks#complete"
  delete '/task/:id' => "tasks#destroy"
  delete '/project/:id' => "projects#destroy"
  # Tasks Routes # 

end

app/models/project.rb
class Project < ActiveRecord::Base
    validates :name, presence: true

    has_many :tasks
    has_many :users, through: :tasks

    scope :filter_by_starts_with, -> (name) { where("name like ?", "#{name.downcase}%")}

    def self.search(search)
        if search.nil? || search.empty?
            flash[:error] = "Search field left blank."
            redirect_to projects_path
        else
            if search
                search_param = Project.find_by(name: search)
                if search_param
                    @result = search_param
                    redirect_to "/project/search"
                else
                    flash[:error] = "No project exists with that name."
                    redirect_to projects_path
                end
            end
        end 
    end 
end 

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :require_login
    before_action :set_project, only: [:show, :edit, :update, :destroy]
    

    def index
        @projects = Project.all
    end
  
    def show
        if !@project.nil?
            @tasks = @project.tasks
        else 
            flash[:success] = "An error occured. Please try again."
            redirect_to projects_path
        end 
    end
  
    def new
        @project = Project.new
    end
  
    def create
        @project = Project.new(project_params)
        @project.user_project_id = current_user.id
        if @project.save
            redirect_to projects_path
        else
            render :new
        end
    end
  
    def edit
        if current_user.id != this_project.user_project_id
            flash[:error] = "You cannot edit a project that doesn't belong to you."
            redirect_to projects_path
        end 
    end
  
    def update
        if @project.update(project_params)
            redirect_to projects_path
        else
            render :edit
        end
    end
  
    def destroy
        if current_user.id != this_project.user_project_id
            flash[:error] = "You cannot destroy a project that doesn't belong to you."
            redirect_to projects_path
        else
            Project.find(params[:id]).destroy
            redirect_to projects_path
        end 
    end
  
    private
  
    def set_project
        if params[:name]
            @project = Project.find_by(name: params[:name])
        elsif params[:id]
            @project = Project.find(params[:id])
        else 
            flash[:error] = "Project either does not exist or an error occuredn. Please check your spelling."
            redirect_to projects_path
        end 
    end

    def this_project 
        Project.find(params[:id])
    end 
  
    def project_params
        params.require('project').permit(:name, :user_id)
    end
  
    def require_login
        if current_user.nil?
            flash[:success] = "You must be logged in to perform this action."
            redirect_to root_path
        end 
    end
end
  

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@project.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @project do |f| %>
    <div class="">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name %>
        <%= f.hidden_field :user_project_id %>
    </div>

    <div class="">
        <%= f.submit "Submit Project", class: "" %>
    </div>

<% end  %>

app/views/projects/edit.html.erb
<br><br><br><br><br>
<%= render 'projects/form',  :locals => {:@project => @project} %>

app/views/projects/index.html.erb
<div class="flash-error">
  <% if flash[:success] %>
    <div class="success">
        <p class="flash-error"><%= flash[:success] %></p>
    </div>
<% end %>
</div>
<br><br>

<h1>Projects</h1><hr>

<a class="task-groups" href="/users/most_projects">Which User Has The Most Projects?</a>

<% @projects.each do |project| %>
  <div class="">
    <h2><%= link_to "#{project.name}", project_path(project)%></h2>
    <% tasks = project.tasks %>
    <%= render partial: 'tasks/tasklist', :locals => {:@tasks => tasks}%>
  </div>
<% end %>

app/views/projects/new.html.erb
<div class=""><br><br><br><br><br>
    <div class="">
        <%= render 'projects/form',  :locals => {:@project => @project} %>
    </div>
</div>

app/views/projects/search.html.erb
<h1><%= @result.query %></h1>

app/views/projects/show.html.erb
<%= flash[:error] if flash[:error] %>
<h1><%= @project.name %></h1><hr>
<% if @project.user_project_id == current_user.id %>
    <%= link_to "Edit Project", edit_project_path(@project) %>
    <%= link_to "Delete Project", "/project/#{@project.id}", method: :delete, data: { confirm: 'Are you sure you want to delete this project?' }  %> </td>
<% end %>
<%= render partial: 'tasks/tasklist', :locals => {:@tasks => @tasks}%>